[package]

name = "mime"
version = "0.3.5" # remember to update html_root_url
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT/Apache-2.0"
description = "Strongly Typed Mimes"
documentation = "https://docs.rs/mime"
repository = "https://github.com/hyperium/mime"
keywords = ["mime", "media-extensions", "media-types"]

[dependencies]
media-type-parser-utils = { git = "https://github.com/1aim/media-type-parser-utils" }
quoted-string = { git="https://github.com/1aim/quoted-string"}
lut = { git = "https://github.com/1aim/lut", features = ["media-type-chars"] }

[features]
inner-bench = []