[package]

name = "mime"
version = "0.3.5" # remember to update html_root_url
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT/Apache-2.0"
description = "Strongly Typed Mimes"
documentation = "https://docs.rs/mime"
repository = "https://github.com/hyperium/mime"
keywords = ["mime", "media-extensions", "media-types"]

[dependencies]
media-type-parser-utils = { path="../media-type-parser-utils" }
quoted-string = { path="../quoted-string"}
# keep the version compatible with the version used in quoted-string
# to make sure there is only one char lookup table in the binary

[dependencies.lut]
path = "../lut"
features = ["media-type-chars"]

[features]
inner-bench = []